//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuscadorInmueble.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inmueble
    {
        public int id_inmueble { get; set; }
        public string distrito { get; set; }
        public string direccion { get; set; }
        public int precio { get; set; }
        public string descripcion { get; set; }
        public string Photo { get; set; }
        public int id_usuario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
